# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('temperature', models.IntegerField(verbose_name='temperature (C°)')),
            ],
            options={
                'verbose_name': 'temperature log',
                'verbose_name_plural': 'temperature logs',
                'ordering': ('-timestamp',),
            },
        ),
    ]
